# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='Album name')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumImageRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_url', models.URLField(help_text='Tweet url were the image appeared', verbose_name='Tweet url')),
                ('notified', models.BooleanField(default=False)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album_creator.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(help_text='Fetched image file', upload_to='uploads/', verbose_name='Image')),
                ('image_url', models.URLField(unique=True, verbose_name='Original image url')),
                ('album', models.ManyToManyField(related_name='images', through='album_creator.AlbumImageRelation', to='album_creator.Album')),
            ],
        ),
        migrations.AddField(
            model_name='albumimagerelation',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album_creator.Image'),
        ),
    ]
