# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Hash tag without the "#" sign, will be used to fetch photos from twitter', max_length=140, verbose_name='Album name')),
            ],
        ),
        migrations.CreateModel(
            name='AlbumImageRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.BigIntegerField(help_text='Used to track last imported photos', unique=True, verbose_name='Tweet ID')),
                ('tweet_url', models.URLField(help_text='Tweet url were the image appeared', verbose_name='Tweet url')),
                ('notified', models.BooleanField(default=False)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_relations', to='album_creator.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(help_text='Fetched image file', upload_to='uploads/', verbose_name='Image')),
                ('image_url', models.URLField(unique=True, verbose_name='Original image url')),
            ],
        ),
        migrations.AddField(
            model_name='albumimagerelation',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_relations', to='album_creator.Image'),
        ),
        migrations.AddField(
            model_name='album',
            name='images',
            field=models.ManyToManyField(related_name='albums', through='album_creator.AlbumImageRelation', to='album_creator.Image'),
        ),
        migrations.AlterUniqueTogether(
            name='albumimagerelation',
            unique_together=set([('album', 'image')]),
        ),
    ]
