# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 11:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('album_creator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumimagerelation',
            name='imported_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 2, 11, 24, 2, 552204, tzinfo=utc), verbose_name='Image import datetime'),
            preserve_default=False,
        ),
    ]
